### ISSUE TITLE
`MutableStack` should have `.view()`

### ISSUE THREAD

**Issue by ice1000** [Glavo/kala-common#46]

**Comment by Glavo** [comment]
Why does it need a view?

**Comment by ice1000** [comment]
> Why does it need a view?

Because I want to traverse it

**Comment by ice1000** [comment]
Maybe we also want Buffer to implement MutableStack, I want an implementation of ArrayStack

**Comment by Glavo** [comment]
> > Why does it need a view?
> 
> Because I want to traverse it

I don't think this is a good idea. Maybe you should use specific implementation classes.

> Maybe we also want Buffer to implement MutableStack

I also think this is not a good idea, because the behavior of each `DynamicSeq` implementation is uncertain.

For example, if `DynamicArray` is used as a stack, it should push the new element to the end; However, for `DynamicLinkedSeq`, it is obvious that the operation of head is efficient.

At present, `DynamicSeq` has `removeFirst` and `removeLast`. I think we can use dynamicseq directly. (I'm preparing for 0.29.0. I'm recalling why I deleted some methods in `DynamicSeq`, which are used in aya)

>  I want an implementation of ArrayStack

This is what I am doing today.

**Comment by ice1000** [comment]
Cooooooooooooooooool!
